# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-11-01 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fortunes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fortune',
            name='contributor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
